const WIDTH = 20;
const HEIGHT = 80;

const CHANCE_GRASS = 50;
const CHANCE_MTN = 15;

const NUMBER_STEPS = 8;

const BIRTH_LIMIT = 5;
const DEATH_LIMIT = 3;

const SNOW_BIRTH = 8;

module.exports = {WIDTH, HEIGHT, CHANCE_GRASS, NUMBER_STEPS, CHANCE_MTN, BIRTH_LIMIT, SNOW_BIRTH, DEATH_LIMIT}



